[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_protocol = esptool

; ========================================================
; ENVIRONNEMENT DE TEST SUR PC (SANS LA CARTE ESP32)
; ========================================================
[env:native]
platform = native
test_framework = googletest
test_ignore = test_embedded  ; Ignore les tests qui ont besoin de l'ESP32

; Force le standard C++17 requis par GoogleTest
build_flags = -std=c++17 -std=gnu++17
build_unflags = -std=gnu++11 -std=gnu++14

; /!\ TRES IMPORTANT : Demande à PlatformIO de compiler aussi le dossier src/
test_build_src = true

build_src_filter =
    -<*>
    +<LowWare/Capteurs/TMP/TMP126.cpp>

